### ISSUE TITLE
Contribution selections are not saved

### ISSUE THREAD

**Issue by chrisys** [pcorbel/scitizen#1]
Firstly: super cool project! I added a device to the open fleet on balenaHub :)

I'm trying to choose the projects I'd like to contribute to, and so I toggled a few of them to the off position. However when I leave the page and return, all the toggles are set to 'on' again - it doesn't appear to be saving the selection. 

Looking at the error messages in the console it's posting to `localhost:3000` instead of the current host (`scitizen.local` in my case).

**Comment by pcorbel** [comment]
Hello @chrisys 👋,
Thanks you for your kind words, and also thanks you for bringing up the first issue of the project 😁

The bug has been fixed and the new version of the app should have already been pushed to your device ✅

Cheers!

**Comment by chrisys** [comment]
Awesome - yes, it now works, thank you! 👍
