### ISSUE TITLE
Contribution selections are lost

### ISSUE THREAD

**Issue by chrisys** [pcorbel/scitizen#5]
Hey there, I noticed my selections for projects to contribute to were lost, I guess as part of an update? Just a heads up (in case you haven't caught it already)! If needed you can store settings on persistent volumes and they'll persist across updates. 👍 

Still loving the project though!

**Comment by pcorbel** [comment]
Hi chrisys, 👋
Thanks a lot for the heads up, and sorry for the disturbance, the project in still in its early days 🙈
The database data should be indeed stored in a persistent volume.
We'll try not to do better next time 🙏
